### ISSUE TITLE
ClusterProfiler Error/External Utils?

### ISSUE THREAD

**Issue by pouryany** [pouryany/PanomiR#35]
**The following build error can be avoided if we make a local version of the function `bitr()` from the clusterProfiler package. We can look into easier ways to address this of course.** 

`  Error: Error: <callr_remote_error: Failed to build source package 'clusterProfiler'>
   in process 9115 
  -->
  Failed to build source package 'clusterProfiler', stdout + stderr:
  
  OE> * installing *source* package ‘clusterProfiler’ ...
  OE> staged installation is only possible with locking
  OE> ** using non-staged installation
  OE> ** R
  OE> ** data
  OE> ** inst
  OE> ** byte-compile and prepare package for lazy loading
  OE> Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  OE>   object 'get_fun_from_pkg' not found
  OE> Error: unable to load R code in package ‘clusterProfiler’
  OE> Execution halted
  OE> ERROR: lazy loading failed for package ‘clusterProfiler’
  OE> * removing ‘/tmp/RtmpUL3O1s/pkg-lib239b6cc4dcf9/clusterProfiler’
  
   Stack trace:
  
   12. (function (...)  ...
   13. base:::withCallingHandlers(cli_message = function(msg) { ...
   14. get("pkg_install_do_plan", asNamespace("pak"))(...)
   15. pkgdepends::install_package_plan(plan = plan, lib = lib, num_workers = num_ ...
   16. base:::withCallingHandlers({ ...
   17. pkgdepends:::handle_events(state, events)
   18. pkgdepends:::handle_event(state, i)
   19. pkgdepends:::stop_task(state, worker)
   20. pkgdepends:::stop_task_build(state, worker)
   21. base:::throw(new_pkg_build_error("Failed to build source package {pkg}",  ...
   22. base:::signalCondition(cond)
   23. (function (e)  ...
   24. base:::stop(e)
   25. (function (e)  ...
  
   x Failed to build source package 'clusterProfiler' 
  
  Execution halted
  Error: Process completed with exit code 1.`

**Comment by hackdna** [comment]
I wonder what's the root cause for this error. Perhaps we can use a precompiled version of clusterProfiler?
